// <auto-generated />
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TaxiService.Migrations
{
    [DbContext(typeof(EFCoreTaxiDbContext))]
    [Migration("20231024193528_Seed")]
    partial class Seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("DataLayer.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DriverId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Class = "Standart",
                            DriverId = 1
                        },
                        new
                        {
                            Id = 2,
                            Class = "Comfort",
                            DriverId = 2
                        },
                        new
                        {
                            Id = 3,
                            Class = "Business",
                            DriverId = 3
                        },
                        new
                        {
                            Id = 4,
                            Class = "Business",
                            DriverId = 4
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Mykola",
                            LastName = "Ivanov",
                            PhoneNumber = "+380733447676"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Ivan",
                            LastName = "Petrov",
                            PhoneNumber = "+380738908888"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Andriy",
                            LastName = "Melnyk",
                            PhoneNumber = "+380731297632"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "Ryan",
                            LastName = "Gosling",
                            PhoneNumber = "+380737663478"
                        });
                });

            modelBuilder.Entity("DataLayer.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CarId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("TripBegin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TripEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DataLayer.Entities.Car", b =>
                {
                    b.HasOne("DataLayer.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("DataLayer.Entities.Order", b =>
                {
                    b.HasOne("DataLayer.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
